version: '3'
services:
  node-app:
    build: .
    ports:
      - '4000:4000'
    volumes:
      # :ro is for the volumes to be read-only
      - ./:/app:ro
      - /app/node_modules
      # exclude DB from the volume read-only
      - /app/src/db
    # environment:
    #   - PORT=4000
    env_file:
      - ./.env
