version: '3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      # :ro is for the volumes to be read-only
      - ./:/app:ro
      - /app/node_modules
      # exclude DB from the volume read-only
      - /app/src/db
    environment:
      - NODE_ENV=development
      - MONGO_USER=sanjeev
      - MONGO_PASS=password
    command: yarn start:dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sanjeev
      - MONGO_INITDB_ROOT_PASSWORD=password
